### ISSUE TITLE
Use in-built Windows Facter facts

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/puppet-windows_power#9]
Use in-built Facter facts and remove the dependency on liamjbennett/win_facts

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.

**Comment by fraenki** [comment]
Good news, we'll continue to maintain this module.

**Comment by Lightning-** [comment]
fixed with the upcoming 4.0.0 release
